### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by T0m555** [T0m555/furima-32868#9]
- フリマアプリのURL
https://furima-32868.herokuapp.com/

- Basic認証のIDとパスワード
user:admin
pass:2222

- 出品者用のメールアドレスとパスワード
meil:test@test.com
pass:123qwe

- 購入者用のメールアドレスとパスワード
mail:test2@test.com
pass:123qwe

- 購入用カードの番号・期限・セキュリティコード
番号:4242424242424242
期限:3/2033
secコード:123

**Comment by snkw-works** [comment]
@T0m555 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
##### 商品出品機能
- [ ] **商品出品画面にて、エラーハンドリングができるよう修正しましょう（適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させること）**
- [ ] **入力に問題がある状態で出品ボタンが押されたら、出品ページに戻りエラーメッセージが表示されるよう修正しましょう**
現状、入力に問題がある状態で出品ボタンをクリックするとエラー画面に遷移してしまい、エラーメッセージが確認できない状態です。
<img width="767" alt="スクリーンショット 2021-04-11 10 31 51" src="https://user-images.githubusercontent.com/54050089/114289228-270d3d00-9ab1-11eb-90b4-13b8d2ec599a.png">


##### 商品編集機能

- [ ] **出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するよう修正しましょう**
現状、ログイン状態の出品者は売却済み商品の商品情報編集ページへ遷移できてしまいます。

- [ ] **商品編集画面にて、エラーハンドリングができるよう修正しましょう（適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させること）**

- [ ] **エラーメッセージの出力は、商品情報編集ページにて行うよう修正しましょう**
現状、入力に問題がある状態で変更ボタンをクリックすると上記と同様のエラー画面に遷移してしまい、エラーメッセージが確認できない状態です。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@T0m555 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、出品機能については修正が確認できました。ありがとうございます！
引き続き、修正していただきたい箇所がございましたので、以下、ご確認をお願いします！

[修正依頼箇所]
##### 商品編集機能
- [x] **出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するよう修正しましょう**
現状、ログイン状態の出品者は売却済み商品の商品情報編集ページへ遷移できてしまいます。

- [x] **商品編集画面にて、エラーハンドリングができるよう修正しましょう（適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させること）**

- [x] **エラーメッセージの出力は、商品情報編集ページにて行うよう修正しましょう**
現状、編集画面にて入力に問題がある状態で変更ボタンをクリックするとエラー画面に遷移してしまい、エラーメッセージが確認できない状態です。
<img width="767" alt="スクリーンショット 2021-04-11 10 31 51" src="https://user-images.githubusercontent.com/54050089/114293780-e2df6400-9ad3-11eb-8724-6ea2e8d215ad.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@T0m555 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、
> 出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するよう修正しましょう

については修正が確認できました。ありがとうございます。
引き続き、修正していただきたい箇所がございましたので、以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **商品編集画面にて、エラーハンドリングができるよう修正しましょう（適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させること）**

- [ ]  **エラーメッセージの出力は、商品情報編集ページにて行うよう修正しましょう**

現状、編集画面にて**販売価格が空欄**の状態で変更ボタンをクリックするとエラー画面に遷移してしまい、エラーメッセージが確認できない状態です。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@T0m555 さん、修正とご提出ありがとうございます‼︎
動作の確認をしたところ、
> ■商品編集画面にて、エラーハンドリングができるよう修正しましょう（適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させること）
■エラーメッセージの出力は、商品情報編集ページにて行うよう修正しましょう

について修正が確認できました。ありがとうございます！
今回、新たに修正していただきたい箇所がございましたので、以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **価格の範囲が、¥300~¥9,999,999の間であるよう修正しましょう**
現状、出品・編集機能にて、300円未満で保存が出来てしまう状態です。（前回挙動確認時には正常に動作しておりました。）

着実に完成へと近付いておりますので、あと少し頑張りましょう！
修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@T0m555 さん、修正とご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new2](https://user-images.githubusercontent.com/54050089/114297255-90f60880-9aea-11eb-8a45-bd861e692157.png)
